#!/bin/bash

read var
echo $var
number_of_lines=`wc --lines < $var`

# using wc command to count number of words
number_of_words=`wc --word < $var`

# Displaying number of lines and number of words
echo "Number of lines: $number_of_lines"
echo "Number of words: $number_of_words"
